import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Jamie James",
  description: "Generated by AI Studio",
};

// Sitewide JSON-LD (Organization/LocalBusiness + WebSite). Injected as a literal
// object by project-writer.ts from verified facts only — never from AI output —
// so this can never contain a fabricated address, phone, or credential.
const SITEWIDE_SCHEMA = [{"@context":"https://schema.org","@type":"Organization","name":"Jamie James","url":"https://example.com","founder":{"@type":"Person","name":"Jamie James"}},{"@context":"https://schema.org","@type":"WebSite","name":"Jamie James","url":"https://example.com"}];

// Design-system fonts (real Google Font names chosen per project by
// designSystem.ts) — loaded via a stylesheet link rather than next/font,
// since next/font requires a static, build-time-known font name and these
// are chosen dynamically per generated project.
const FONT_HEADING = "Playfair Display";
const FONT_BODY = "Inter";
const GOOGLE_FONTS_HREF = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(
  FONT_HEADING
)}:wght@400;500;600;700&family=${encodeURIComponent(FONT_BODY)}:wght@400;500;600&display=swap`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link rel="stylesheet" href={GOOGLE_FONTS_HREF} />
      </head>
      <body
        className="bg-background text-foreground antialiased font-body"
        style={
          {
            "--font-heading": `'${FONT_HEADING}', sans-serif`,
            "--font-body": `'${FONT_BODY}', sans-serif`,
          } as React.CSSProperties
        }
      >
        {SITEWIDE_SCHEMA.map((schema: Record<string, unknown>, i: number) => (
          <script
            key={i}
            type="application/ld+json"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
          />
        ))}
        {children}
      </body>
    </html>
  );
}
